config/routes.rb
Rails.application.routes.draw do
  resources :loans
  resources :books
  root 'home#index'
  get 'home/about'

  get 'search',to:"books#search"
  get 'about_book',to:"home#about_book"
  get 'preview',to:"home#book_preview"
  get 'admin',to:"admin#admin"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  get "password/reset/edit", to: "password_resets#update"

  

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  resources :users do
    collection { post :import }
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def about
  end

  def book
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
         <%= image_tag "ELibrary.png", height: 45 %>
        <small class="d-block mb-3 text-muted">© 2021/2022</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
        </ul>
      </div>
    </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">

    <%= link_to root_path do %>
      <%= image_tag "ELibrary.png", height: 80, class: "height: 70px; margin-left: 4%;" %>
    <% end %>
    
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <%# <ul class="navbar-nav me-auto mb-2 mb-md-0">
      </ul> %>
      <form class="d-flex" style="margin: auto;" action="/search">
        <input class="form-control me-2" style="width: 70vh;" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light me-3" type="submit">Search</button>
      </form>

      <%= link_to 'Home', root_path, class: "btn btn-info me-3" %> |
      </div>
      

    <% if user_signed_in? %>

        <%= link_to "Account", edit_user_registration_path, class: "btn btn-outline-info me-3" %>
        <%= link_to "MyBooks", loans_path, class: "btn btn-outline-info me-3" %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-info me-3" %>

        <% if @user.admin == 1 %>

            <%= link_to "Admin", admin_path, class: "btn btn-outline-light me-3" %>

        <% end %>

        <% else %>

        <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-info me-3", style:"font-weight: bold;"%>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-info me-3", style:"" %>

      <% end %>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/about_book.html.erb
        <% 
        #Example.api_call

        response = RestClient.get('https://www.googleapis.com/books/v1/volumes?q='+params[:id]+'&projection=lite')
        books_array = JSON.parse(response)
        #raise books_array.to_json
        %>

        <% books_array['items'].each do |book|%>
        
        <% #poskrbi da se vedno pokaze knjiga z enakim id-jem
        if book['id'] != params[:id]
            next
        end %>
        
        

        <%  if book['volumeInfo']['imageLinks']
            @cover = book['volumeInfo']['imageLinks']['thumbnail']
        else
            @cover = 'smiley.png'
        end
        if  book['volumeInfo']['description']
            @description = book['volumeInfo']['description']
        else
            @description = 'no description'
        end
        if book['volumeInfo']['authors']
            @author = book['volumeInfo']['authors'].join(', ')
        else @author = 'unknown author'
        end
        @title = book['volumeInfo']['title']
        @id = book['id']
        %>
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg" style="background-image: url('unsplash-photo-3.jpg');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold"><%= book['volumeInfo']['title'] %></h2>
                <ul class="d-flex list-unstyled mt-auto">
                <li class="d-flex align-items-center me-3">
                    <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                </ul>
            </div>
            </div>
        </div>

        
        <%break%>
        <% end %>


<div class="container">
  <div class="row">
    <div class="col-4">

        <div class="cover">
            <br><br>
            <img width="180px" src="<%= @cover %>">
            <br><br><br>
            <% link_to 'Read', preview_path(id: @id), method: :get, class:'btn btn-primary read' %>
            
            <%
            @loans = Loan.all 
            #check if there are any loans
            %>

            <%if user_signed_in? %>
            
            <% if (Loan.where( "book_id = ? AND user_id = ? AND loan_expiration_date > ?", @id, current_user.id, Date.today).count) == 1 %>
                <%= link_to 'Read', preview_path(id: @id), method: :get, class:'btn btn-primary read' %>
                <% elsif(Loan.where( "book_id = ? AND user_id != ? AND loan_expiration_date > ?", @id, current_user.id, Date.today).count) == 1%>
                    The book is currently on loan.
                    It will be available on: <% @loan = (Loan.where( "book_id = ? AND loan_expiration_date > ?", @id, Date.today).first)%> <%= @loan.loan_expiration_date.strftime("%d. %B %Y") %> 
                    
                <% else %>
                <%=
                    button_to 'Borrow', {:controller => "loans", :action => "create", :book_id => @id, :user_id=> current_user.id, :loan_date=> Date.today, :loan_expiration_date=> 7.days.from_now} , :method=>:post, class:'btn btn-primary read'
                %>
            <% end %>
            <% else %>
                <%= link_to 'Borrow', new_user_session_path , :method=>:post, class:'btn btn-primary read'
                %>
            <% end %>

        </div>
    
    </div>
    <div class="col-8">
        <br><br>
        <div>
            <h1><%= @title %></h1>
            <br>
            <p><%= @description %></p>
            <i>by <%= @author %></i>
        </div>
    
    </div>
  </div>
</div>

app/views/home/book_preview.html.erb
<script type="text/javascript" src="//books.google.com/books/previewlib.js"></script>
<script type="text/javascript">
GBS_insertEmbeddedViewer('<%=params[:id]%>',1100,1000);
</script>

app/views/home/index.html.erb
<main>

    <div id="slider">
   <div class="slides">
      <!-- First slide --> 
      <div class="slider">
         <div class="legend"></div>
         <div class="content">
            <div class="content-txt">
               <h1> Read free books online </h1>
               <h2> Millions of books available through Controlled Digital Lending </h2>
            </div>
         </div>
         <div class="images"> 
            <%= image_tag "slider1.jpg", style: "width: -webkit-fill-available;" %>
         </div>
      </div>
      <!-- Second slide --> 
      <div class="slider">
         <div class="legend"></div>
         <div class="content">
            <div class="content-txt">
               <h1> Keep Track of your Favorite Books </h1>
               <h2> Organize your Books using Lists & the Reading Log </h2>
            </div>
         </div>
         <div class="images"> 
            <%= image_tag "slider2.jpg", style: "width: -webkit-fill-available;" %>
         </div>
      </div>
      <!-- Third slide --> 
      <div class="slider">
         <div class="legend"></div>
         <div class="content">
            <div class="content-txt">
               <h1> Be an Open Librarian </h1>
               <h2> Dozens of ways you can help improve the library </h2>
            </div>
         </div>
         <div class="images"> 
            <%= image_tag "slider3.jpg", style: "width: -webkit-fill-available;" %>
         </div>
      </div>
      <!-- Fourth slide --> 
      <div class="slider">
         <div class="legend"></div>
         <div class="content">
            <div class="content-txt">
               <h1> Try Fulltext Search </h1>
               <h2> Find matching results within the text of millions of books </h2>
            </div>
         </div>
         <div class="images"> 
            <%= image_tag "slider4.jpg", style: "width: -webkit-fill-available;" %>
         </div>
      </div>
   </div>
</div>




        <!--<h2>Import Users</h2> -->

        <%#= form_tag import_users_path, multipart: true do %>
        <%#= file_field_tag :file %>
        <%#= submit_tag "Import" %>
        <%# end %>
        


        <% 
        url = 'https://www.googleapis.com/books/v1/volumes?q=book&projection=lite&maxResults=3'

        #Example.api_call
        #https://www.googleapis.com/books/v1/volumes?q=Potter+subject:fiction&maxResults=20
        response = RestClient.get('https://www.googleapis.com/books/v1/volumes?q=Potter&maxResults=5&filter=partial')
        books_array = JSON.parse(response)
        #raise books_array.to_json
        %>

        
        <h2 class="pb-2 border-bottom" style="margin-left: 120px">Books We Love</h2>
        <br><br>

        <div class="container">
            <div class="row">
                <% books_array['items'].each do |book|%>
                    <div class="col imag">
                        <%= link_to about_book_path(id: book["id"]), method: :get do %>
                            <div class="col imag" style="background-image: url(<% if (book['volumeInfo']['imageLinks']) %><%= book['volumeInfo']['imageLinks']['thumbnail'] %><% end %>); background-repeat:no-repeat;  width:200px; height:290px !important"></div>
                        <% end %>
                    </div>
                <% end %>
        </div>
        </div>
        
        <br><br>
        <h2 class="pb-2 border-bottom" style="margin-left: 120px">Fiction books</h2>
        <br><br>
        <%response = RestClient.get('https://www.googleapis.com/books/v1/volumes?q=subject:fiction&filter=partial&maxResults=5')
        books_array = JSON.parse(response)%>
        <div class="container">
            <div class="row">
                <% books_array['items'].each do |book|%>
                    <div class="col imag">
                        <%= link_to about_book_path(id: book["id"]), method: :get do %>
                            <div class="col imag" style="background-image: url(<% if (book['volumeInfo']['imageLinks']) %><%= book['volumeInfo']['imageLinks']['thumbnail'] %><% end %>); background-repeat:no-repeat;  width:200px; height:290px !important"></div>
                        <% end %>
                    </div>
                <% end %>
        </div>
        </div>

        <br><br>
        <h2 class="pb-2 border-bottom" style="margin-left: 120px">Drama books</h2>
        <br><br>
        <%response = RestClient.get('https://www.googleapis.com/books/v1/volumes?q=subject:drama&filter=partial&maxResults=5')
        books_array = JSON.parse(response)%>
        <div class="container">
            <div class="row">
                <% books_array['items'].each do |book|%>
                    <div class="col imag">
                        <%= link_to about_book_path(id: book["id"]), method: :get do %>
                            <div class="col imag" style="background-image: url(<% if (book['volumeInfo']['imageLinks']) %><%= book['volumeInfo']['imageLinks']['thumbnail'] %><% end %>); background-repeat:no-repeat;  width:200px; height:290px !important"></div>
                        <% end %>
                    </div>
                <% end %>
        </div>
        </div>




    <br><br>
        <h2 class="pb-2 border-bottom" style="margin-left: 120px">Thriller books</h2>
        <br><br>
        <%response = RestClient.get('https://www.googleapis.com/books/v1/volumes?q=subject:thriller&filter=partial&maxResults=5')
        books_array = JSON.parse(response)%>
        <div class="container">
            <div class="row">
                <% books_array['items'].each do |book|%>
                    <div class="col imag">
                        <%= link_to about_book_path(id: book["id"]), method: :get do %>
                            <div class="col imag" style="background-image: url(<% if (book['volumeInfo']['imageLinks']) %><%= book['volumeInfo']['imageLinks']['thumbnail'] %><% end %>); background-repeat:no-repeat;  width:200px; height:290px !important"></div>
                        <% end %>
                    </div>
                <% end %>
        </div>
        </div>
</main>



  