config/routes.rb
Rails.application.routes.draw do
  resources :loans
  resources :books
  root 'home#index'
  get 'home/about'

  get 'search',to:"books#search"
  get 'about_book',to:"home#about_book"
  get 'preview',to:"home#book_preview"
  get 'admin',to:"admin#admin"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  get "password/reset/edit", to: "password_resets#update"

  

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  resources :users do
    collection { post :import }
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]

  # GET /loans or /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1 or /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans or /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to about_book_path(id: @loan.book_id), notice: "You have successfully borrowed the book." }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1 or /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to loan_url(@loan), notice: "Loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1 or /loans/1.json
  def destroy
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      #params.require(:loan).permit(:book_id, :user_id, :loan_date, :loan_expiration_date)
      params.permit(:book_id, :user_id, :loan_date, :loan_expiration_date)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_with(model: loan) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :loan_date %>
    <%= form.datetime_select :loan_date %>
  </div>

  <div class="field">
    <%= form.label :loan_expiration_date %>
    <%= form.datetime_select :loan_expiration_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align:center;">Loans</h1>

<div class="container">
  <div class="row">
    <div class="col">
      
    </div>
    <div class="col">
        <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Cover image</th>
            <th>Title</th>
            <th>Loan expiration</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @loans.each do |loan| %>
          <% 
              #Example.api_call

              response = RestClient.get('https://www.googleapis.com/books/v1/volumes?q='+loan.book_id+'&projection=lite')
              books_array = JSON.parse(response)
              #raise books_array.to_json
              %>

              <% books_array['items'].each do |book|%>
              
              <% #poskrbi da se vedno pokaze knjiga z enakim id-jem
              if book['id'] != loan.book_id
                  next
              end %> 

              <% if loan.user_id == current_user.id %>
              <tr>
              <td> 
              <div class="container">
                  <div class="row">
                          <div class="col imag" style="margin-right: 50px;">
                              <%= link_to about_book_path(id: book["id"]), method: :get do %>
                                  <div class="col imag" style="background-image: url(<% if (book['volumeInfo']['imageLinks']) %><%= book['volumeInfo']['imageLinks']['thumbnail'] %><% end %>); background-repeat:no-repeat;  width:200px; height:290px !important"></div>
                          </div>
                      <% end %>
              </div>
              </div>
              </td>
              <td> <div class="container">
                  <div class="row">
                          <div class="col imag">
                          <%= book['volumeInfo']['title'].truncate(50) %>
                          </div>
              </div>
              </div></td>
              
              <td style="border-left: 1px dotted black"><div  class="container"><%= loan.loan_expiration_date.strftime("%d. %B %Y") %></div></td>
              
              
              <td><% link_to 'Show', loan %></td>
              <td><% link_to 'Edit', edit_loan_path(loan) %></td>
              <td style="font-weight: bold;"><div class="container"><%= link_to 'Delete my Loan', loan, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger me-3" %></div></td>
            </tr>
            <% end %>
          <% end %>

              
              <% end %>

          
        </tbody>
      </table>
    </div>
    <div class="col">
      
    </div>
  </div>
</div>

<br>

<% link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @loan.book_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @loan.user_id %>
</p>

<p>
  <strong>Loan date:</strong>
  <%= @loan.loan_date %>
</p>

<p>
  <strong>Loan expiration date:</strong>
  <%= @loan.loan_expiration_date %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>